version: '3.8'

# FAST BUILD VERSION - For development with slow internet
# Uses Dockerfile.fast which skips heavy ML packages

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: insurance-kb-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../api
      dockerfile: Dockerfile.fast
    container_name: insurance-kb-api
    ports:
      - "8000:8000"
    volumes:
      - ../api:/app
      - ../data:/data
    env_file:
      - ../.env
    environment:
      - QDRANT_URL=http://qdrant:6333
      - PYTHONUNBUFFERED=1
      # Use OpenAI embeddings to skip sentence-transformers requirement
      - EMBEDDINGS_PROVIDER=openai
    depends_on:
      qdrant:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    container_name: insurance-kb-web
    ports:
      - "3000:3000"
    volumes:
      - ../web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    command: npm run dev

volumes:
  qdrant_storage:
    driver: local


